### ISSUE TITLE
Fix find-lexical-variables for LispWorks

### ISSUE THREAD

**Issue by Yehouda** [numcl/specialized-function#2]
find-lexical-variables  can be made to work in LispWorks by the documented sys:map-environment :
#+lispworks
(defun find-lexical-variables (env)
  (let ((list nil))
    (sys:map-environment env :variable #'(lambda (name kind info)
                                           (declare (ignore info))
                                           (when (and (eq kind :lexical)
                                                      (symbol-package name))
                                             (push name list))))
     (delete-duplicates (nreverse list))))

This assumes that gensyms are not interesting. 
Maybe it can do other checks, like checking for specific package, checking for pattern in the name, or maybe even pass it a function to check if  a variable is interesting. For example, when it is used by specializing which is used by numcl.impl::einsum-lambda, numcl.impl::einsum-lambda can pass down a function that checks if the variable appears in the einsum-vars structure.

**Comment by guicho271828** [comment]
plz wait until I settle in a new location (Boston)

**Comment by guicho271828** [comment]
Hi,
Do you intend to submit a pull request?
I don't know your email address and afraid I fail to give a credit to your code.

This function must detect all lexical symbols. Only several of them (specified by the user) are used for dispatching. Everything else is just passed to each dispatched code as is.

**Comment by guicho271828** [comment]
ping

**Comment by guicho271828** [comment]
Hi, is your email address Yeh@Maldoo.com ? I found it from your past papers.

**Comment by Yehouda** [comment]
>  
>  Hi, is your email address Yeh@Maldoo.com ? I found it from your past papers.
>  

yeh@maldoo.com is my private email address, yeh@lispworks.com is the
work address. 

I normally use yeh@lispworks.com for discussing Lisp issues, because
it is part of my work.

**Comment by guicho271828** [comment]
ok I will set the authorship of a new commit to your address.
